### PR TITLE
Update translations from Transifex

### PR DESCRIPTION
**Pull request by ArneBab**

### CODE REVIEW

**Comment by xor-freenet** [comment]
In case you used the shell to download these off Transifex, can you please tell me the commands you used?

I'd like to both document this in a commit message as well as using it to reproduce your results.

Thanks!

**Comment by xor-freenet** [comment]
@ArneBab wrote by mail:
> https://github.com/freenet/scripts/blob/master/transifex-pull

Thanks! Will try to deal with shipping a testing release within the next week.

**Comment by xor-freenet** [comment]
@ArneBab 

It seems like  I don't even have read-access to the Transifex repo of WoT
anymore, the Transifex tool fails to download the translations with:
> Error: Authentication failed. Please make sure your credentials are valid.

I can log on to the website, however it shows that I'm not part of the Freenet
organization anymore, so that's probably the reason.

I suppose adding me back with WoT/FT access only won't hurt anyone?
If yes can you deal with that please - if you don't know how IIRC Steve does?
The username is `xor_freenet`.

I can say that this effort seems worth it as it already showing some benefit:
While reviewing the `transifex-pull` script you provided I found that there is
indeed already some difference in the way you've been pulling the translations
as compared to the version I had been using with WoT previously (only found
it now that I remembered what it was called, sorry).
So I would like to compare the results of those two approaches once I have
access.
Also I'll try to make more l10n-releases in the future in return :)

**Comment by ArneBab** [comment]
Transifex "invite maintainer" says that it does not know xor_freenet. Can you log in to your account?

**Comment by xor-freenet** [comment]
@ArneBab 
> Transifex "invite maintainer" says that it does not know xor_freenet. Can you log in to your account?

Thanks for trying to fix this!
Yes I can log onto the website and I had copy-pasted the username from there.
I would blind-guess your problem is for the same reason as I had stated in my original message:

> I can log on to the website, however it shows that I'm not part of the Freenet
> organization anymore, so that's probably the reason.

Specifically, I would say it might be possible that you have to add me to the organization so you can invite me as maintainer?
Notice that this is merely a guess, I never administrated Transifex.

**Comment by xor-freenet** [comment]
Any news on this? :) Notice that I had replied to your remaining question :)
And thanks for all the merges today! :)

**Comment by xor-freenet** [comment]
Sorry but I'm forced to temporarily pseudo-merge this instead of doing a real merge:
- I must file PRs to your branch `master` to replace Travis with GitHub Actions, and they need to be `--ff-only`-capable as discussed.
- However I cannot file `--ff-only`-capable PRs without merging this into my repo before.
- I cannot merge it without the capability to review it before, which I don't have due to lack of Transifex access.
- But waiting for someone to provide TX access has been taking too long now.
- Hence I will pseudo-merge it meanwhile: Merge it along with commits which immediately revert it again.
- I will document this by closing the PR before so it is not marked as merged.

Once I've been provided access to Transifex I will do a real merge, i.e. revert the reverts.
You don't have to spend time on this for now, I am fine with delaying l10n updates until I finish the IdentityFetcher-rewrite.

**Pull request closed without merging**
